CREATE USER C##Dora IDENTIFIED BY aaa;
SHOW USER;
GRANT CREATE SESSION TO C##Dora;

ALTER USER C##Dora IDENTIFIED BY aaa;
PASSWORD C##DORA;

COMMIT;

CONNECT C##Dora/aaa;
SHOW USER;

PASSWORD;

-- profile
CREATE PROFILE C##LIMITED_PROFILE LIMIT
FAILED_LOGIN_ATTEMPTS 3;

ALTER USER C##Dora PROFILE C##LIMITED_PROFILE;

-- lock - unlock
ALTER USER C##Dora ACCOUNT LOCK;
ALTER USER C##Dora ACCOUNT UNLOCK;