show user;

CREATE PROFILE C##LIMITED_WITH_TIME LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    ;

CREATE USER C##test IDENTIFIED BY test;

GRANT CREATE SESSION TO C##test;

ALTER USER c##test PROFILE c##LIMITED_WITH_TIME;

-- manually unlock
ALTER USER c##test ACCOUNT UNLOCK;

-- altering profile
ALTER PROFILE C##LIMITED_WITH_TIME LIMIT
    PASSWORD_LIFE_TIME 10
    PASSWORD_GRACE_TIME 8
    PASSWORD_REUSE_MAX 3
    PASSWORD_REUSE_TIME UNLIMITED;

select * FROM USER_USERS;
commit;