show user;

CREATE PROFILE C##LIMITED_WITH_TIME LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    ;

CREATE USER C##MHN IDENTIFIED BY mhn;

GRANT CREATE SESSION TO C##MHN;

ALTER USER c##MHN PROFILE c##LIMITED_WITH_TIME;

-- manually unlock
ALTER USER c##MHN ACCOUNT UNLOCK;

-- altering profile
ALTER PROFILE C##LIMITED_WITH_TIME LIMIT
    PASSWORD_LIFE_TIME 10
    PASSWORD_GRACE_TIME 8;

select * FROM USER_USERS;